name: Erik Hårdén
favicon: null
layout_spectrum: 0.18577961716800928
typography_spectrum: 0.9212477267719805
title: 'Nörd, pappa och entreprenör'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7630664822645485
  lightness: 0.680080424528569
  saturation: 0.11305056791752577
  rhythmicContrast: 0.7167325662449002
purpose: []
