name: Erik Hårdén
favicon: null
layout_spectrum: 0.18577961716800928
typography_spectrum: 0.9212477267719805
title: 'Nörd, pappa och entreprenör'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#211f20'
    - '#4f4e49'
    - '#fdf9f0'
    - '#78766a'
    - '#a39d85'
  brandStrength: 0.3125
  lightness: 0
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
